export const QUERY_KEYS = {
  ONBOARDINGDETAILS: "onboarding-details",
  DEPARTMENTS: "all-departments",
  DEPARTMENT: "department",
  PERMISSIONS: "all-permissions",
  ROLES: "roles",
  ROLE: "role",
  USERS: "users",
  INVITED_USERS: "invited-users",
  DIRECTORY_USERS: "directory-users",
  UNINVITED_USERS: "uninvited-users",
  USER: "user",
  EXPENSE_CATEGORIES: "expense-categories",
  DIRECTORY: "directory",
  PURCHASE_REQUESTS: "purchase-requests",
  PURCHASE_REQUEST: "purchase-request",
  PROCUREMENT_CATEGORIES: "procurement-categories",
} as const;
