"use client";

import Image from "next/image";
import { Check, ShieldCheck } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { cn } from "@/lib/utils";
import { useOnboardingStore } from "@/stores/useVilletoStore";

import { ONBOARDING_STEPS as steps } from "@/lib/constants/onboarding-steps";

const stepDetails: Record<string, string> = {
  onboarding: "Your setup overview",
  business: "Company profile",
  leadership: "Owners and officers",
  financial: "Spend and banking",
  products: "Choose your tools",
  review: "Confirm and submit",
};

const getInitials = (name: string) => {
  if (!name) return "";
  const words = name.trim().split(" ");
  return words.length >= 2 ? `${words[0]?.[0] ?? ""}${words[1]?.[0] ?? ""}`.toUpperCase() : name.substring(0, 2).toUpperCase();
};

export const OnboardingSidebar = () => {
  const pathname = usePathname();
  const router = useRouter();
  const { stoppedAtStep, businessSnapshot } = useOnboardingStore();
  const pathSegment = pathname === "/onboarding" ? "onboarding" : pathname.split("/").filter(Boolean).pop();
  const isVerifyOtp = pathname.includes("verify-otp");
  const matchedStep = steps.find((step) => step.key === pathSegment);
  const currentStep = matchedStep?.id || (isVerifyOtp ? stoppedAtStep || 1 : 1);
  const currentStepData = steps.find((step) => step.id === currentStep) ?? steps[0];
  const progress = ((currentStep - 1) / (steps.length - 1)) * 100;
  const autoGenerated = businessSnapshot.businessName?.includes("@");
  const businessName = autoGenerated ? "" : businessSnapshot.businessName || "";
  const navigateTo = (step: (typeof steps)[number]) => {
    if (step.id >= currentStep || isVerifyOtp) return;
    router.push(step.id === 1 ? "/onboarding" : `/onboarding/${step.key}`);
  };
  return (
    <>
      <header className="sticky top-0 z-30 border-b border-black/[0.07] bg-white px-5 py-4 lg:hidden">
        <div className="flex items-center justify-between gap-4">
          <Image src="/images/logo.png" alt="Villeto" width={118} height={36} className="h-8 w-[106px] object-cover" priority />
          <span className="rounded-full bg-[#e7f6f2] px-3 py-1.5 text-[10px] font-semibold text-[#087f70]">Step {currentStep} of {steps.length}</span>
        </div>
        <div className="mt-3 flex items-center justify-between gap-4">
          <p className="truncate text-[12px] font-semibold text-[#1a211e]">{currentStepData.title}</p>
          <div className="h-1.5 w-28 overflow-hidden rounded-full bg-[#e7ece9]">
            <div className="h-full rounded-full bg-[#0ea894] transition-[width] duration-500" style={{ width: `${progress}%` }} />
          </div>
        </div>
      </header>
      <aside className="hidden w-[40%] shrink-0 flex-col bg-[#0b100e] px-8 py-8 text-white lg:flex xl:px-10">
        {currentStep >= 3 && businessName ? (
          <div className="flex h-9 items-center gap-3">
            {businessSnapshot.logo ? (
              <Image src={businessSnapshot.logo} alt="Company logo" width={36} height={36} className="size-9 rounded-full bg-white object-contain" />
            ) : (
              <span className="flex size-9 items-center justify-center rounded-full bg-[#0ea894] text-[11px] font-semibold text-[#07100d]">{getInitials(businessName)}</span>
            )}
            <span className="truncate text-[13px] font-semibold">{businessName}</span>
          </div>
        ) : (
          <Image src="/images/logo.png" alt="Villeto" width={132} height={40} className="h-9 w-[118px] object-cover brightness-0 invert" priority />
        )}
        <div className="mt-10">
          <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#6edbca]">Workspace setup</p>
          <h2 className="mt-3 text-[22px] font-semibold leading-tight tracking-[-0.02em]">Build your company profile</h2>
          <p className="mt-2 text-[12px] leading-5 text-white/48">Complete each section once. You can return to finished steps at any time.</p>
        </div>
        <nav aria-label="Onboarding progress" className="mt-9 flex-1">
          <ol>
            {steps.map((step, index) => {
              const isCurrent = step.id === currentStep;
              const isComplete = step.id < currentStep && !isVerifyOtp;
              return (
                <li key={step.id} className="relative pb-1 last:pb-0">
                  {index < steps.length - 1 && <span className={cn("absolute left-[22px] top-[38px] h-[26px] w-px", isComplete ? "bg-[#0ea894]" : "bg-white/12")} />}
                  <button type="button" onClick={() => navigateTo(step)} disabled={!isComplete} aria-current={isCurrent ? "step" : undefined} className={cn("flex w-full items-center gap-3 rounded-[9px] px-2 py-2.5 text-left transition-colors", isCurrent && "bg-white/[0.07]", isComplete && "cursor-pointer hover:bg-white/[0.04]", !isCurrent && !isComplete && "cursor-default opacity-42")}>
                    <span className={cn("relative z-10 flex size-7 shrink-0 items-center justify-center rounded-full border text-[10px] font-semibold", isComplete && "border-[#0ea894] bg-[#0ea894] text-[#07100d]", isCurrent && "border-[#53d3c0] bg-[#15352f] text-[#8ce5d7]", !isComplete && !isCurrent && "border-white/20 bg-[#111714] text-white/45")}>{isComplete ? <Check className="size-3.5" strokeWidth={2.6} /> : step.id}</span>
                    <span className="min-w-0">
                      <span className={cn("block truncate text-[12px] font-semibold", isCurrent ? "text-white" : "text-white/72")}>{step.title}</span>
                      <span className="mt-0.5 block truncate text-[10px] text-white/38">{stepDetails[step.key]}</span>
                    </span>
                  </button>
                </li>
              );
            })}
          </ol>
        </nav>
        <div className="mt-8 flex items-start gap-3 border-t border-white/10 pt-5">
          <span className="flex size-8 shrink-0 items-center justify-center rounded-[8px] bg-[#15352f] text-[#6edbca]"><ShieldCheck className="size-4" /></span>
          <div>
            <p className="text-[10px] font-semibold">Secure onboarding</p>
            <p className="mt-1 text-[9px] leading-4 text-white/38">Your progress is saved as you continue.</p>
          </div>
        </div>
      </aside>
    </>
  );
};
